### ISSUE TITLE
panic due to network reconnection

### ISSUE THREAD

**Issue by Lichmaker** [wendy512/iec104#1]
使用了demo进行测试，输出日志如下：
```
cs104 client => 2024/07/11 17:14:10 [D]: connecting server tcp://10.8.3.219:2404
cs104 client => 2024/07/11 17:14:10 [D]: connect success
cs104 client => 2024/07/11 17:14:10 [D]: run started!
cs104 client => 2024/07/11 17:14:10 [D]: recvLoop started
cs104 client => 2024/07/11 17:14:10 [D]: TX uFrame U[function: StartDtActive]
cs104 client => 2024/07/11 17:14:10 [D]: handlerLoop started
cs104 client => 2024/07/11 17:14:10 [D]: sendLoop started
cs104 client => 2024/07/11 17:14:10 [D]: TX Raw[68 04 07 00 00 00]
cs104 client => 2024/07/11 17:14:11 [D]: RX Raw[68 04 0b 00 00 00]
cs104 client => 2024/07/11 17:14:11 [D]: RX uFrame U[function: StartDtConfirm]
cs104 client => 2024/07/11 17:14:11 [D]: TX iFrame I[sendNO: 0, recvNO: 0]
cs104 client => 2024/07/11 17:14:11 [D]: TX iFrame I[sendNO: 1, recvNO: 0]
cs104 client => 2024/07/11 17:14:11 [D]: TX iFrame I[sendNO: 2, recvNO: 0]
cs104 client => 2024/07/11 17:14:11 [D]: TX iFrame I[sendNO: 3, recvNO: 0]
cs104 client => 2024/07/11 17:14:11 [D]: TX Raw[68 0e 00 00 00 00 64 01 06 00 01 00 00 00 00 14]
cs104 client => 2024/07/11 17:14:11 [D]: TX Raw[68 0e 02 00 00 00 65 01 06 00 01 00 00 00 00 05]
cs104 client => 2024/07/11 17:14:11 [D]: TX Raw[68 14 04 00 00 00 67 01 06 00 01 00 00 00 00 f9 2b 0e 09 8b 07 18]
cs104 client => 2024/07/11 17:14:11 [D]: TX Raw[68 0f 06 00 00 00 68 01 06 00 01 00 00 00 00 aa 55]
cs104 client => 2024/07/11 17:14:11 [D]: RX Raw[68 0e 4c 00 12 00 64 01 07 00 01 00 00 00 00 14]
cs104 client => 2024/07/11 17:14:11 [D]: RX Raw[68 0e 4e 00 12 00 64 01 0a 00 01 00 00 00 00 14]
cs104 client => 2024/07/11 17:14:11 [D]: RX iFrame I[sendNO: 38, recvNO: 9]
cs104 client => 2024/07/11 17:14:11 [E]: fatal incoming acknowledge either earlier than previous or later than sendTime
cs104 client => 2024/07/11 17:14:11 [D]: RX Raw[68 14 50 00 16 00 67 01 07 00 01 00 00 00 00 f9 2b 0e 09 8b 07 18]
cs104 client => 2024/07/11 17:14:11 [E]: receive failed, read tcp 10.8.3.15:61346->10.8.3.219:2404: use of closed network connection
cs104 client => 2024/07/11 17:14:11 [D]: recvLoop stopped
cs104 client => 2024/07/11 17:14:11 [D]: sendLoop stopped
cs104 client => 2024/07/11 17:14:11 [D]: handlerLoop stopped
cs104 client => 2024/07/11 17:14:11 [D]: run stopped!
cs104 client => 2024/07/11 17:14:11 [D]: disconnected server tcp://10.8.3.219:2404
cs104 client => 2024/07/11 17:14:12 [D]: connecting server tcp://10.8.3.219:2404
cs104 client => 2024/07/11 17:14:12 [D]: connect success
cs104 client => 2024/07/11 17:14:12 [D]: run started!
cs104 client => 2024/07/11 17:14:12 [D]: recvLoop started
cs104 client => 2024/07/11 17:14:12 [D]: sendLoop started
cs104 client => 2024/07/11 17:14:12 [D]: TX uFrame U[function: StartDtActive]
cs104 client => 2024/07/11 17:14:12 [D]: handlerLoop started
cs104 client => 2024/07/11 17:14:12 [D]: TX Raw[68 04 07 00 00 00]
cs104 client => 2024/07/11 17:14:12 [E]: sendRaw failed, write tcp 10.8.3.15:61365->10.8.3.219:2404: use of closed network connection
cs104 client => 2024/07/11 17:14:12 [D]: sendLoop stopped
cs104 client => 2024/07/11 17:14:12 [D]: handlerLoop stopped
cs104 client => 2024/07/11 17:14:12 [E]: receive failed, read tcp 10.8.3.15:61365->10.8.3.219:2404: use of closed network connection
cs104 client => 2024/07/11 17:14:12 [D]: recvLoop stopped
cs104 client => 2024/07/11 17:14:12 [D]: run stopped!
panic: sync: negative WaitGroup counter

goroutine 20 [running]:
sync.(*WaitGroup).Add(0xc0000fe000?, 0x4b03640?)
        /usr/local/go/src/sync/waitgroup.go:62 +0xd8
sync.(*WaitGroup).Done(...)
        /usr/local/go/src/sync/waitgroup.go:87
github.com/wendy512/iec104/client.(*Client).Connect.func1(0xc0000fe0e8?)
        /Users/wuguozhang/go/pkg/mod/github.com/wendy512/iec104@v1.0.0/client/core.go:93 +0x38
github.com/wendy512/go-iecp5/cs104.(*Client).run(0xc0000fe000, {0x4b0aec0, 0xc0000e4140})
        /Users/wuguozhang/go/pkg/mod/github.com/wendy512/go-iecp5@v1.2.3/cs104/client.go:311 +0x4e2
github.com/wendy512/go-iecp5/cs104.(*Client).running(0xc0000fe000)
        /Users/wuguozhang/go/pkg/mod/github.com/wendy512/go-iecp5@v1.2.3/cs104/client.go:151 +0x3db
created by github.com/wendy512/go-iecp5/cs104.(*Client).Start in goroutine 1
        /Users/wuguozhang/go/pkg/mod/github.com/wendy512/go-iecp5@v1.2.3/cs104/client.go:115 +0x5a
exit status 2
```

出现问题在这里：
<img width="825" alt="截屏2024-07-11 17 15 23" src="https://github.com/wendy512/iec104/assets/8957712/66e3e779-9843-4ba0-8219-bc339c7e2729">

第93行的 `wg.Done()` 是在 `OnConnectHandler` 中，但重连的时候会重复执行handler，导致 `wg.Done()` 被多次执行。  
有一个很大的疑问，请问这里的waitgroup作用是什么呢？ 100行里的timeout判断是出于什么考虑？

**Comment by wendy512** [comment]
100行里的timeout主要判断连接成功后才能发送启动激活，如果第一次连接不成功直接抛出error，而不是程序启动后再进行重试，93行的`wg.Done()`判断下是不是第一次连接即可

**Comment by wendy512** [comment]
bug已修复，请获取最新版本`go get -u github.com/wendy512/iec104@v1.0.1`
